### ISSUE TITLE
My Applications Security

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#1082]
Currently in the WIP My Applications piece, we're using query parameters to navigate to various applications. In order to view an individual application you need to be logged in, but that is the only level of security put in place. If I knew or guessed the ID to another application, I could put it in the URL and view another application / someone else's personal information.

I don't know if we currently have any other places in the app where we are restricting data by user. If not, we need to figure out how we'd like to do this so we can standardize role based security in the application.

**Comment by pbn4** [comment]
Hey Emily, guessing another applications ID and putting it in query param will yield a 403 from the backend request if you are not the owner of it, an admin or a leasing agent for a given listing this applications has been submitted for. Main source of such logic is in the backend, frontend does not really enforce any security on the data because one can e.g. skip it completely and use a tool like Postman to interact with our backend. So basically backend makes no assumptions about who is the client of the API: browser, mobile, postman, shell etc and if the client enforces any security.

**Comment by pbn4** [comment]
We do not have an automated test that checks it but we a have similar one where an unauthenticated user cannot retrieve an application (knowing the ID) of another user.

**Comment by emilyjablonski** [comment]
@pbn4 Thanks for the reply here! When I have the application open locally on my branch, I am able to take an application id from a different user's application and view it. For example I log-in as `test2@example.com` and copy one of their application ids, and then log-in with `admin@example.com`, and if I put test2's application ids into the URL, it does still load even though I'm logged in as a different user and I see all their info. Is this maybe behavior that works differently locally?

**Comment by kathyccheng** [comment]
@emilyjablonski are we good on this one then, can we close?

**Comment by emilyjablonski** [comment]
Good to close 👍
