### ISSUE TITLE
CSV Export Broken in Partners 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1094]
When I click Export CSV, I get an empty CSV file 

![image](https://user-images.githubusercontent.com/3453407/113066450-8a7d9d80-9188-11eb-98d8-924daf3ebb2a.png)

**Comment by kathyccheng** [comment]
@dominikx96 @pbn4 can one of you guys look into this? thanks!

**Comment by pbn4** [comment]
@kathyccheng I hotfixed it on housingbayarea/0.3_alameda only. I didn't want to merge our generic repo master because I was unsure what changes in there should/should not go into alameda.

**Comment by pbn4** [comment]
@kathyccheng The main problem was the code was not handling correctly a nulled monthly income scenario. My hotfix added a fallback for such code errors (I will actualy fix it on bloom main repo), in case of any unexpected errors a `null` value will be inserted into a row instead of crashing a request with 500.

**Comment by dominikx96** [comment]
@kathyccheng I also created a new issue to create an error alert in the frontend side: #1095
It's a frontend improvement, which can be merged separately from the backend hotfix. I'll prioritize it :)

**Comment by kathyccheng** [comment]
Closed

**Comment by kathyccheng** [comment]
Reopening to fix properly on Bloom @pbn4
