### ISSUE TITLE
Figure out a way to customize emails for SMC 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1097]

**Comment by pbn4** [comment]
Requirement: being able to determine which public site user is browsing in order to e.g. change an appropriate email template.

Options that I see we have are:

1. Add custom HTTP header to each request - can be easily done with https://docs.netlify.com/routing/headers/ : 
   ```
   ```
2. Reuse existing HTTP headers like e.g. `Origin`, but there are some caveats: 
   ```
   Basically, browsers add the Origin request header to:

   all cross origin requests.
   same-origin requests except for GET or HEAD requests (i.e. they are added to same-origin POST, OPTIONS, PUT, PATCH, 
   and DELETE requests).
   ```

**Comment by dominikx96** [comment]
For me, 1st solution makes sense! (after testing, but I'm pretty sure it should work as expected).

**Comment by software-project** [comment]
I also like the headers solution. But it's only the first part of this issue. Second is translations. Should we store the in the DB in file, for each county? Commiting translation files as jsons on the long run to a "universal" backend might not be the best idea. We will have an entity to hold counties in so having just a json translation field there would be plenty enough. As it's going to be mostly for emails.

**Comment by kathyccheng** [comment]
Closing, covered with footer updates for now
