### ISSUE TITLE
Listings management: migrating to the new schema

### ISSUE THREAD

**Issue by pbn4** [bloom-housing/bloom#1269]
Problem: based on what we already have from working on listings CMS we will change the listings model so much that it will require adjusting existing Alameda prod site we have already deployed. 

Here are my proposed solution:
 - move existing API to /v1 global route prefix and adjust that immediately
 - develop an adapter layer /v2 which will be compatible with the new API model but old underyling DB model
 - migrate existing sites to /v2 
 - remove the adapter logic and implement /v2 using the new data model (migrate DB to the new model), from this point all not migrated v1 sites will break

Note 1: For fields that are new in v2 we just add them immediately to v1, they should not be breaking changes.

@seanmalbert Let me know your thoughts on this.

**Comment by seanmalbert** [comment]
Hey @pbn4 ,

This pretty much aligns with what I was thinking as well, but with some key differences. Here's what I was thinking:

- keep existing routes as v1, so we don't have to immediately do anything
- As we start introducing db changes for v2 API to use, we develop and maintain an adapter layer to keep v1 working without any changes needed to the current sites
- v2 then, wouldn't need the adapter (since it's only for v1), and would directly use the new data model
- once everything is migrated to v2, we can drop the adapter and deprecate the old API

So the major difference between your proposal and mine is when the DB model is updated and what the adapter is applied to.

What do you think? I'm not against your approach and maybe we need to do a pros/cons list for each approach.
