### ISSUE TITLE
Text Error in Partners for Coliseum 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1284]
Looks like one string still needs to be updated here, it should be Oakland Housing Authority Project-Based Vouchers 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/7d7890d0-671d-4472-9a7d-7ab9611f0f18)

**Comment by seanmalbert** [comment]
@emilyjablonski ,

I fixed the bug that was causing the issue. Please see https://partners.housingbayarea.bloom.exygy.dev/application/05c4ed65-19bb-45eb-aac9-7953320b71d7. Sorry I didn't see the override was set to `Oakland Housing Authority` instead of `Oakland Housing Authority Project-Based Vouchers` or I would have updated that too.
