### ISSUE TITLE
Decide on a React forms library and implement an initial form with validation

### ISSUE THREAD

**Issue by jacchau** [bloom-housing/bloom#131]

**Comment by bk3c** [comment]
Since we're about to have a lot more forms as part of Bloom, it's a great time to pick a React form library that can handle some of the plumbing for us.

I don't know if there are any specific must-haves, other than support for existing stack elements (e.g. Typescript, nextjs). Other than that, the goal is (as per usual) the most useful functionality, with the least amount of engineering overhead.

I think we're open to any reasonable solution, but the current leading contenders in my mind are (in no particular order):

- [React Hook Form](https://react-hook-form.com/)
- [Formik](https://jaredpalmer.com/formik)
    - +[yup](https://github.com/jquense/yup)?
- [React Final Form](https://final-form.org/react)

**Comment by bk3c** [comment]
Some relative sense of popularity can be found here: https://www.npmtrends.com/formik-vs-react-final-form-vs-react-hook-form-vs-informed. As always, I don't feel like we need to pick the most popular, so long as there's enough critical mass to imply a stable and evolving upstream.

**Comment by jaredcwhite** [comment]
I did some side-by-side tests of those three form options, and in many respects the API and functionality is pretty consistent across all three. So it's hard to pick a clear winner right off the bat. However, when looking at where React is going with hooks and that API design style, I feel like React Hook Form is the most "modern" approach designed from the ground up. The documentation is pretty good as well and the pace of GH updates and releases is impressive. It also looks like React Hook Form can use yup schemas for validation which is cool. So I'd feel good about that option unless there's a gotcha I'm not yet aware of.

**Comment by bk3c** [comment]
@akegan do you have any thoughts or feedback on this one? From Jared's prototyping + my own reading, I think we're likely to try React Hook Form and see how it goes as we start to implement applications, but if you have any thoughts or feedback as someone with the peculiarities of what needs to be done, they'd be most welcomed.

**Comment by akegan** [comment]
We just switched to react-final-form for the partners app last year so I'd prefer to stick with that if there's no particular issue with it. It's not totally perfect (we're having a hard-ish time with currency fields, for example), but we're familiar with it at least so that helps. 

I also appreciate that react-final-form has a much longer track record and is maintained by someone who was also built a different form library in the past https://final-form.org/docs/react-final-form/philosophy
Another consideration is that we initially built it with react-form which then died pretty soon after we started the project, incurring lots of tech debt to switch over

**Comment by jaredcwhite** [comment]
@akegan Thanks, very useful feedback!

As an aside, I did notice some conversation on Final Form's GH about how they've added support for React hooks, but it was hard to figure out how that works from their docs. Probably would just need to spend some more time with it.

**Comment by bk3c** [comment]
I'm (belatedly) closing this since we seem pretty settled on React Hook Form, in favor of #135 where development will continue. We're definitely still taking feedback there or wherever is convenient as people have opinions.
