### ISSUE TITLE
Build v0 of a Notifications Service to support sending Email Notifications

### ISSUE THREAD

**Issue by jacchau** [bloom-housing/bloom#132]
Initial functionality to allow:

- [ ] Sending an email notification. The calling service (e.g. the Application Service to call when a new application is submitted) should be able to queue up an email, and then it should be sent as soon as reasonable.
- [ ] ~~We need to catch the case where the email API isn't available for any reason, and make sure we can try again later.~~ Split off to #498
- [ ] The content of the message should also be passed in at send time, though maybe in some future version we could consider templates?

**Comment by bk3c** [comment]
Ok, we're ready to move forward on this so that we can send emails for both user password resets / invites, and also for application submittal confirmations. I'll be splitting some of the features off into other issues, so the initial focus should just be on sending emails.

We have an account with Sendgrid all set up for dev and testing whenever it's needed. Contact me offline for an API key.

**Comment by bk3c** [comment]
Not sure if it's a perfect fit since I think we ultimately want to support notifications by text in addition to email, but there's already at least two nestjs module wrappers for for sendgrid. https://github.com/anchan828/nest-sendgrid seems like the more promising one from my quick look. 

There are also a number of popular wrappers for nodemailer, but I'm not sure that's the route we want to take since I'm pretty sure we'll want to use more functionality from the API than we'd get with a straight SMTP send. I'm not too worried about vendor lock-in in the foreseeable future.
