### ISSUE TITLE
Basic User Flows: Account Creation/Onboarding, Login, Manage User Account, List Applications

### ISSUE THREAD

**Issue by jacchau** [bloom-housing/bloom#134]
This is the front-end **public** user UI for #133. We'll eventually have a complementary UI in the partners portal. Key Elements

**Account Creation / Onboarding**
- [ ] collect basic account information: real name, email, phone number
- [ ] email or text confirmation / validation flow. We'll eventually need both, but it should be fine to only do one for this v0 implementation. Note that the logic should be primarily in the User/Auth service (which should then call the Notifications Service, but we obviously need the matching screens in the Public UI for the user to land on. 

**Login**
- [ ] show a login button/link in the header bar, conditionally replaced with the user name (and links to manage user account / logout) if the user is already logged in
- [ ] allow the user to login with a user name and password
- [ ] allow the user to logout

**Manage User Account** (or maybe Manage Profile?)
- [ ] show current account information
- [ ] update account information

**List Applications** (maybe My Applications?)
- [ ] get from the Application Service and show a list of all applications that the current user has submitted
- [ ] allow the user to click on an application and see the detailed content of their submission

This is way bigger than we should do in 1 PR. We can either use this issue as a meta and then open specific issues for PR-sized tasks as we take them on, or we can keep all of the detailed discussion here and just link the appropriate PRs back to this issue, whichever makes more sense to folks.

**Comment by bk3c** [comment]
Note: I think it'll take quite a bit of time to build this and all of the dependancies out, so we should either put it behind a site-level feature flag or otherwise figure out a way to hide the functionality from users without making it too difficult to keep the live sites up to date with the code base. 

The idea of site feature flags seems like it might be generally useful long-term, since we'll undoubtably have more situations like this, but I'm open to ideas since I don't have a clear implementation in my mind.

**Comment by kathyccheng** [comment]
@bk3c we have a bunch more issue regarding user flows now, can I close this one out?
