### ISSUE TITLE
Google Analytics Tracking Off

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1343]
When I go to Google Analytics, traffic drops sharply after 5/29. From the debugger, it seems like the call is firing, but it's not showing up in their UI. The number of views is not 0, it's 24 from a smattering of referral sources on a number of pages including the homepage and City Center.

**Comment by seanmalbert** [comment]
The issue ended up being that a GTM_KEY value in the netlify config file was overwriting the value set in the environment variables within Netflify's config. It was using `GTM-W8LH9F9` instead of `GTM-M686WH4`. So the traffic was going to the account for bloom.exygy.dev, see https://analytics.google.com/analytics/web/#/report/content-pages/a165693279w231581863p217631120/_r.drilldown=analytics.pagePath:~2Fapplications~2Fstart~2Fchoose-language%3FlistingId=18735b00-89a1-49c1-932a-a5fbe5fb5d73/

The site has been updated and is now using the correct key and we're seeing traffic flow into the right account now.

**Comment by seanmalbert** [comment]
This is also updated in core now.
