### ISSUE TITLE
Listings: Rankings & Results MVP 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1383]
**Goal**: Leasing agent should be able to specify details about lotteries and waitlists

**Fields**:
Field Name | Entity Model | Type | Current State | Required
------------ | ------------- | --- | ----- | -----
Listing Type |  | string null | No | Yes
Lottery Date | ? | string null | Yes | If enabled
Is Waitlist Open | isWaitlistOpen | boolean | Yes | Yes
Display Waitlist | displayWaitlist | string null | Updates needed | Yes
Max Waitlist Size | waitlistMaxSize | string null | Updates needed | If enabled
Current Waitlist Size | waitlistCurrentSize | string null | Updates needed| If enabled
Open Spots on Waitlist |  | string null | No | If enabled

**Acceptance Criteria:**
- User can select Lottery
   - If Lottery Listing Type selected, show a Lottery Date field
- If Waitlist is Open, show an option to Display Waitlist size
- If Display Waitlist is yes, show Maximum Waitlist Size, Current Waitlist Size and Open Spots on Waitlist 

**Public**
- Display Waitlist should show or hide waitlistMaxSize, waitlistCurrentSize, Open Spots on Waitlist instead of just waitlistMaxSize

Notes
* For now, let's only support the lottery type for now
* Also dropping the results section, see screenshot below 

![image.png](https://images.zenhubusercontent.com/5f0361f3c34cb3aabaf096f2/304af2e0-29f4-45e1-8da1-8833ab722f2a)

**Figma**:
Default:
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=2722%3A125596

Lottery:
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=2722%3A125742

Waitlist:
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=2722%3A125882

Waitlist Size Yes:
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=2722%3A125967

Waitlist Size No:
https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=2722%3A126118

Original Issue: #1178

**Comment by seanmalbert** [comment]
There are two main changes to the code that need to happen around waitlist.

### isWiatlistOpen
Currently isWaitlistOpen is computed based off of `waitlistCurrentSize < waitlistMaxSize`, we want to change that because developers/agents should be able to say that the waitlist is open without specifying the waitlist current size and max size.

This field should be made its own boolean column in the model.

### waitlistOpenSpots
This is also currently a computed field (openSlots) with = `waitlistMaxSize - waitlistCurrentSize`. We also want this to be moved to its own number column on the model.
