### ISSUE TITLE
Listings Address: Update and Migrate - MVP+1

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#1417]
We want to take advantage of the address model and remove the use of jsonb columns for listing addresses. There are a few parts to this:

1. So that the address model can stay usable for other relationships and so that we can be more flexible in the addresses related to a listing, create a listingXAddress model, with the following columns:
    1. listing_id
    2. address_id
    3. type - new enum of `application, agent, pickup`
2. Add this relationship to the listing and address models
3. create a script which migrates the addresses from the old jsonb columns to the address table, inserting the applicable relationships into the listingXAddress table and remove the old column
4. update the ListingDto with the following:
    1. omit address
    2. expose a definition for each of the addresses with their old names and transform listing.address so that it returns the corresponding address of that type

**Comment by pbn4** [comment]
@seanmalbert What is the addvantage of having a separate table instead of `application_pickup_adddres_id` etc columns directly in Listing model?

**Comment by seanmalbert** [comment]
@pbn4 
If the same address can be used for multiple purposes like pickup and dropoff, then having a separate table makes sense, and they can both reference the same address id, and per your comment in the thread, it sounds like we can do away with the cross table.

**Comment by pbn4** [comment]
@seanmalbert In https://github.com/bloom-housing/bloom/pull/1439 you wrote a comment:

>Also, unitType is still defined here as a string, which I don't think we want anymore with this update. With that in mind, wouldn't we also want a script to create a the unit types based off of these strings and assign them accordingly?

Same issue applies here: what should I do in a case where `applicationAddress` column of type `jsonb` should be converted to a ManyToOne relation with the same property name? It will break v1 because TypeORM will create a migration dropping `applicationAddress` column, rewriting the migration to smoothly move data from `jsonb` to the other table will also break v1 because ORM has to join the other table now instead of just selecting the column by default. That's why in https://github.com/bloom-housing/bloom/pull/1439 I introduced an alternative name to leave the old property for backwards compatibility purposes.

**Comment by ludtkemorgan** [comment]
This was addressed in PR #1512
