### ISSUE TITLE
Investigate why ala.bloom.exygy.dev is so slow 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1551]
Figuring out what's causing the slowdown

**Comment by kathyccheng** [comment]
@seanmalbert @pbn4 did we address this already?

**Comment by seanmalbert** [comment]
The issue was patched for alameda, but the underlying issue still exists, where it can take over ten seconds for the backend to respond to a /listings request, which caused an issue with the cache tries and revalidates (it essentially couldn't in time, so it was always hitting the database). There are several pieces underway to speed up listing requests, like the ami chart work @pbn4 is doing in #1575, which the concept can scale to other relationships , and discussion/prototyping around #1563 .

**Comment by kathyccheng** [comment]
Okay closing this issue then
