### ISSUE TITLE
State machine set up for status change

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1582]
@seanmalbert to fill out details

**Comment by seanmalbert** [comment]
We're moving the conversation started in #1541 here to do this work as a blocker to #1541, #1542 and #1580.

**Comment by dominikx96** [comment]
Hey,

I’ve started researching possibilities for how we can implement validators for different states.
For now - I think for state management, [xstate](https://xstate.js.org/docs/) (+ @xstate/react which provides helpful hooks) is the best choice.

To summarize we can assume:
- Validators:
    - draft (probably only one field is required)
    - active (most of the fields are required)
- States:
    - draft | active
- Transitions:
    - draft -> draft (validator: draft)
    - draft -> active (validator: active)
    - active -> draft (validator: draft)
    - active -> active (validator: active)

Each transition should define a proper validation and store information about it.

The main consideration that I have is about what kind of validation we want on the frontend side.
Of course, backend validation still should be implemented.

**1. Frontend and backend validation:**
    - We can create a group of rules which can be shared between frontend and backend, then fetch it from the API during the build and apply proper rules for each field depending on the state and transition after event e.g after clicking on the “publish” button

    - Pros:
        - A better UX, a user don’t need to wait for the API response
        - We still meet with validation patterns like in the other forms in the app (data is validated on both sides)

**2. Backend only validation:**
    - We can validate form data backend side only and return an object with errors from the API, then:
        - map each one backend id with the frontend id
        - map each one validation rule (e.g. required) to a proper frontend value to determine which translation show

I feel like the second option has a similar complexity as the first, because:
- We still have to determine which backend field ID is on the frontend
- We still have to show proper translations

so far - the first option seems to better work for me.

I also think, if we consider implementing a “form configurator” in the future - it’s a good time to think about how we want to build this solution to easily use it in the future without many breaking changes.

**How we can connect backend field names with the frontend?**
Do we plan to create a static object in the frontend app or create a new entity to store frontend field keys?

Do you have any thoughts before we go deeper? :)

**Comment by jaredcwhite** [comment]
I agree with @dominikx96 — either option (1) or (2), we still have a similar amount of work to build a validation rules engine that is compatible with the shape of the JSON.

Thinking of what we can leverage that's already out there…does anyone have experience with Yup? https://github.com/jquense/yup

React Hook Form has an integration point: https://react-hook-form.com/get-started#SchemaValidation

**Comment by seanmalbert** [comment]
We want to start with a POC that takes react-hook-form and creates a simple field/validation map to trigger a validation hook to test out @dominikx96's option 1 from above and using https://github.com/jquense/yup. 

React hook form and yup resolver.
https://github.com/react-hook-form/resolvers/tree/master/yup

In this POC, please consider how we handle validating data for the form that is not a "field", but is stored in the state. Take Units, for example, which is a group of fields. We want Units to be required, and it should be easy enough to define that in the validation schema, check it against the data, but how do we display that at the field group level? Is there a component that react hook form provides to let us easily do that or do we need to update our GridSection component to receive error and errorMessage props?

**Comment by seanmalbert** [comment]
Should be ready for Monday

**Comment by kathyccheng** [comment]
Closing
