### ISSUE TITLE
Create distinction between partner and public users

### ISSUE THREAD

**Issue by seanmalbert** [bloom-housing/bloom#1616]
From the discussion thread, we need to create a distinction between public and partner users. Rather than create a simple flag, we can do this via role assignment. We currently have two roles in the system, admin and user (and technically anonymous). We can assign the admin and user roles to partner users and leave it so public users have no role.

Since the system is already using Casbin, we can leverage that and add in the use of the [RBAC API](https://casbin.org/docs/en/rbac-api#addroleforuser), which allows us to easily assign a role to a user. So when creating a new user for Partners Portal, we would also call `addRoleForUser("<user_id>", "<role>"}`.

Then instead of the logic we have now to check if a user is an admin or is assigned to listings (in the case of a leasing agent) to build out their roles, we can simply call `hasRoleForUser("<user_id>", "<role>")`.

If we also update the logic of assigning a leasing agent to a user to use something like `addRoleForUser("<user_id>", "listing_<listing_id>")`, then we can clean up the logic in `authz.service` even further.

@willrlin's comment below:

Just wanted to write down here so I didn't forget - @seanmalbert and I spoke yesterday about this and realized that there needs to be a distinction between public users and partner portal users such that if Detroit wanted to enable partner portal users to create new listings, we wouldn't also accidentally enable public users to create listings.

_Originally posted by @willrlin in https://github.com/bloom-housing/bloom/discussions/1570#discussioncomment-1130519_

**Comment by abbiefarr** [comment]
@seanmalbert what does the timeline look for this work? Our team would love to have this for Detroit, I'd be happy to pick it up if it's not coming up soon on your roadmap.

**Comment by seanmalbert** [comment]
@abbiefarr ,
We can get to this in the next two weeks, likely started at the end of next week, so if you can pick it up sooner, I would really appreciate it.

**Comment by abbiefarr** [comment]
Thanks @seanmalbert, I'll plan to pick this up this week!

**Comment by abbiefarr** [comment]
Putting some thoughts here for feedback.

My plan was to create a new table, with structure `user_id | is_admin | is_partner` where `user_id` is a primary foreign key from the `user_accounts` table, and join the two tables. Note that `is_partner` is just a rename of the old `user` role.

Thinking about how this migration would go, since AFAIK there's currently no way to distinguish between public and partner (non admin) user accounts. For Detroit, this is no big deal because we don't have any accounts anyway. But for other users, we'll need to be more thoughtful with the migration.

My initial thought is to grant all users `is_partner` access. Essentially that's no change from the state we're in now, and would be less disruptive than temporarily revoking partner access for everyone. It also means we could go ahead and harden the authz policy. However, it would require manually revoking partner access from all public users at some point, which isn't ideal if there are lots of user accounts.

Alternatively, we could revoke partner access for everyone but not lock down authz until the partner flag has been flipped for all partners. That may be a better approach if there are many fewer partners than public users, but I'm hesitant to suggest this because it seems like it could involve coordinating with all Bloom forks, if they're inheriting your auth policy. With the first approach, you can update your policy at any time and it shouldn't affect any forked sites.

@seanmalbert let me know if you have any thoughts, or if there's anything I'm missing here.

**Comment by abbiefarr** [comment]
Womp, thanks to @seanmalbert for helpfully pointing out the `listings_leasing_agents_user_accounts`, which solves all my problems. :)
