### ISSUE TITLE
Blake Berkeley - Greystar - Customizations 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#1769]
**Customizations Needed** 
* Household size by AMI chart should be Unit Type by AMI. This should be covered in the use BMR chart option. Final output should look like this 

![image](https://user-images.githubusercontent.com/3453407/135290369-c7e8831a-ad9f-47d9-9e98-e141019fec8b.png)

**Comment by seanmalbert** [comment]
@kathyccheng , I made an update to only show the unit types that were selected for Household Maximum Income. So now we only see studio, one and two bedroom. https://housing.acgov.org/preview/listings/d526acd4-a038-4eff-b917-77dd448fbbb6. I'm not sure if the pricing is right in that section, since one and two are showing the same. So let me know if it looks like there needs to be an update around that too.
