### ISSUE TITLE
MFA Back End Work

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2224]
As part of the partner portal security protocol updates, we want to support both email and SMS authentication. A user will choose one option. Based off of their selection, whenever the user logs in, they will be sent a security code and will have to enter that code to successfully login.

What we need to cover in this issue:
1. the ability to generate a one-time password OTP
2. store the users preference between email or sms
3. setup sendgrid to use Twilio for SMS (Twilio owns sendgrid and should be easy)
4. upon a user logging into the system, they should be sent a message with the code
5. a mfa confirm endpoint, which checks the user's code against the generated one

Considerations:
The OTP should have an expiration, so that after n number of minutes, the user will have to start the process again, so we will need to handle this use case.

**Comment by seanmalbert** [comment]
Questions that were asked in planning:
1. do we want to have them choose each time?
2. should we confirm the email/phone number the first time to ensure that they entered it correctly before sending them a code?

**Comment by seanmalbert** [comment]
@pbn4,
1. we decided on yes, they will choose each time
2. We don't need to send a separate confirmation aside from the code. For email, we know that is correct, because they log in/receive an invite email with it. If the user chooses phone and they have not yet used the phone number for authentication, we will give the user the opportunity to change the phone number, since they could have entered it wrong and not received a code. That means we two things:
  1. we want to store if a user's phone number was successfully used for authentication
  2. we want to be able to send a confirmation code to a phone number without it yet being saved to the user's account

This covers the cases where a phone number was added for a user by an admin, but it's wrong, or a phone number is getting added for the first time by the user during the MFA process.

**Comment by pbn4** [comment]
> we want to be able to send a confirmation code to a phone number without it yet being saved to the user's account
 
Doesn't it defeat the purpose of MFA if I can provide a device at log in time (even if for the first time)?

Q1. Are we going to enable MFA for every partners user in a bulk? 

Flow:
1. User tries to log in as usual by providing email and password
2. Backend checks email and password, if it's correct it responds with 401 with message `{message: mfaRequired, authType: email/sms}`, at this point there has to be some information in the DB telling backend whether to send an email or an SMS and whether MFA is enabled for this user. If the email and password pair is not correct normal 401 message is returned (this kinda leaks the information that user has MFA enabled but on the other hand noone can spam user's email/phone without knowing the password). 
3. User reads the code and sends the credentials again but this time with additional field `mfaCode`
4. Backend checks email, password, mfaCode and it's expiration date and accepts/declines log in.

The only necessary changes are related to `POST /auth/login` endpoint.

**Comment by seanmalbert** [comment]
> Doesn't it defeat the purpose of MFA if I can provide a device at log in time (even if for the first time)?

I think I see your point. If a person always selected email then their phone would never be setup, so someone could get the username and password and select phone for the "first time" and get in. We do want to avoid this scenario, which we can do by limiting it to the first time they use MFA, not just the first time they're using their phone for MFA. The user would have to use their email and then go to their profile to add a phone number.

If the user's account is already compromised when we introduce MFA, whether we have them setup MFA immediately after providing their email and password or have them go to a profile page to do it, doesn't seem to add any real level of security.

> Q1: Are we going to enable MFA for every partners user in a bulk?

Yes in that they won't have an option not to use it, but I'm not sure what action we would be taking in bulk for the users when we release this. Can you elaborate?

> Q2: What do you think about user being enable to switch on and off MFA in user's profile page?

I think doing this would defeat the purpose of having MFA, if users can decide not to use it. This would be a viable option if it were the partner portal user's data we are trying to protect, because it would be them opting in or out to protect their own data.

**Comment by seanmalbert** [comment]
@pbn4 , here are the figma files which contain all of the copy @pbn4 , here is the figma files for MFA, which contains all of the copy https://www.figma.com/file/Y8bFd0aSz7eYJ2TCNid6s3/bloom-partners?node-id=4649%3A181148
