### ISSUE TITLE
Translations Solution 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#2390]
**Current Problems** 
* For existing languages / sites, it's hard to know which strings on the public side still need to be translated / we're missing translations for. We will not need to translate partners. 
* For a new language, it's hard to pull all of the necessary strings to send over 
* It's hard to send over a file to the translators 
* It's hard to take the translated files and add them back in 

**Goals**
* Explore solutions to more easily pull needed translations and secondarily manage the translations process
* I'd like to consider Phrase since the SF team uses it but I'm not sure if we're set up to utilize it well

**Comment by emilyjablonski** [comment]
Concerns 1-3 seem like the same thing to me - we want to easily get a list of untranslated strings for any language.

We can push up our existing JSON file and Phrase will import the strings. Phrase would then be able to easily identify any missing translations in their UI. It identifies per language the missing strings and those can then be inputted in the UI by anyone. We can then manually pull from Phrase the string diffs. They do have webhooks that could check for string change events automatically, but I don’t think we’d want to be frequently fetching strings on the fly. 

We already have a script that identifies every missing string & we could continue to massage that into any format, so I’m not sure of the benefit here from Phrase. The only small benefit I see is that when we modify an existing key today, we have to make a new key instead of changing it so that it’s clear the foreign keys are outdated. In this case, Phrase would know to mark the foreign keys as unverified when we change the English key.

I think if you have a more complex system in which you have multiple environments that need to use the same translations, or you are changing translations very frequently and want to fetch them in real time, Phrase makes sense.

Regardless of what we choose we would still need to separate out public and partners site strings to only translate the public site. 

For concern 4, if our translators are not going to use Phrase themselves / login the site and enter the translations, then it would still just as manual of a process for us in terms of transferring over the strings from whatever format they give us into Phrase, which is the same amount of effort we are already doing for new strings into the JSON files. If they are going to log-in to Phrase and look at the missing strings themselves translate them there so we can pull through the API, this would save us some time.

The Phrase Basic Plan is $28 / user / month

**Comment by emilyjablonski** [comment]
Notes from standup: Potentially we could use the existing script and export the strings in a more readable way such that we could send them directly to translators, and have some formate the translators abide by (likely just like our listing spreadsheet) so that we can have another script that automatically imports them. We would still have the somewhat manual work of separately public and partners strings. One suggestion is to have the public strings in a core file and extend any partners-only strings on top of them in a separate file.
