### ISSUE TITLE
Core - Public What to Expect Get Started in Application (SJ)

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3032]
As a resident
I want to better understand the process for a waitlist vs vacant unit opportunities 
So that I can be prepared 

**Acceptance Criteria**
* When I am on the get started page in the application, then I will see different what to expect text for Waitlist, FCFS, and Lottery type listings

**Notes**
* Translations are still pending

**Designs** 
https://www.figma.com/file/5fGM1vGvQCmnhLCDkuqROr/Public-What-to-Expect?node-id=8%3A3030
![image](https://user-images.githubusercontent.com/3453407/187776631-1d3ff56d-2203-4e53-a2e0-77822f066b6b.png)

**Content**
(The Get Started Rows) 
https://docs.google.com/spreadsheets/d/1zrZb9WFRJ2qFPIyfkFGK_BkeQ1_ejk7j9qYuxO35mOs/edit#gid=1891467199

**Product Brief**
https://docs.google.com/document/d/1905UwGoceAskeNlEjRcIoShDMgENcnE6PXzxewECGro/edit#heading=h.jhuf99j9fm9

**Comment by jaredcwhite** [comment]
Just making a note: this appears to be a port of similar functionality from Alameda.

**Comment by jaredcwhite** [comment]
@kathyccheng A couple of things I'm confused about:

* This is marked SJ but it's in the core Bloom repo? Should this be relocated to housingbayarea?
* I'm not sure how the third open waitlist option is determined relative to FCFS and Lottery, since there are two separate database fields. Is it only an option along with FCFS, or does it "override" both FSFS and Lottery settings? (This might be a question for @YazeedLoonat …)

**Comment by kathyccheng** [comment]
LGTM
