### ISSUE TITLE
Moving away from monorepo spike 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3205]

**Comment by ludtkemorgan** [comment]
Findings:
- UI-Components:
  - This has already been pulled out
- Backend:
  - This has no dependencies on the other packages.
  - Only very minor changes needed to pull it out and work independently. e.g update tsconfig.json
  - Will need to keep publishing it to npm as front-end's depend on the typing. Potentially could just publish the types directory
- Public:
  - Dependent on backend, shared-helpers, and ui-components.
  - Need to either publish shared-helpers or pull those helpers into public. Preferably publish it since partners needs it too.
- Partners:
  - Dependent on backend, shared-helpers, and ui-components.
  - same changes needed as Public.

Overall, pulling the packages out from being a monorepo would be fairly straight forward. Minimal changes would be needed to the code, mostly around configuration. Main thing that would be required is to continue publishing the backend types and to start publishing the shared-helpers. 

At this time I do not see any benefit to pulling it out of monorepo configuration, but in the future it could be beneficial if we want to have jurisdictions that don't use our partners and/or backend service.
