### ISSUE TITLE
Set up GA4 on dev

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3213]
This is the current dev environment that's hooked up, we should maybe update it to a new URL: https://analytics.google.com/analytics/web/?authuser=1#/report-home/a165693279w231581863p217631120

**Comment by kathyccheng** [comment]
I think it should be pointing to this one: https://dev-bloom.netlify.app/

**Comment by sarahlazarich** [comment]
snippet for the current dev instance:


<script async src="https://www.googletagmanager.com/gtag/js?id=G-KRK27XFF6M"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-KRK27XFF6M');
</script>

**Comment by ColinBuyck** [comment]
QA Notes: Since https://dev-bloom.netlify.app/ has been deleted for https://hba-public-main.netlify.app/, the hba-public site is now tracking using the above information. This can be tested by navigating through pages on the netlify site and then seeing that reflected in the Realtime tab in Google Analytics under Views by Page title and screen.

**Comment by sarahlazarich** [comment]
looks good to me! I see my movement through the site (https://hba-public-main.netlify.app/additional-resources) tracked on the GA4-Dev account.
