### ISSUE TITLE
Performance Spike based on heroku output 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3216]
The Heroku Postgres instances give good insight into the database queries. Specifically slow/non-performant ones along with the most frequently used ones. 

https://data.heroku.com/datastores/c11c3134-44ac-4e72-8632-924b0e3e54a4#diagnose

This Spike is to go through the queries listed there and see if there are easy and/or important changes that we can do to increase the performance

Time box this to a few days.

Outcome of this spike:
- Identify what queries can be optimized and create stories to address them.
-

**Comment by ludtkemorgan** [comment]
Findings:
- Relatively Detroit doesn’t really have slow queries. Should focus on HBA. (slowest query in Detroit averages under 20ms whereas slowest in HBA can get above 1 second)
- Several queries listed in Heroku for HBA could be considered slow, the most prominent being for getting users and applications.

Users findings:
- The slowest overall query. Can get over 1 second on average.
- Unable to get the full query since Heroku truncated the output. 
- Did a local EXPLAIN on an estimated query and actual was 2.174ms planning vs 6.385ms execution.
  - My guess is that the times listed are not accurate compared to production, but could be a good indicator of the ratio between planning and execution.

Applications finding:
- Two separate queries show up in the slow list. One for application total counts and one for getting the distinct applications.
  - I believe the count one is used for getting the counts on the left side of the applications page
- Each query is roughly ~500ms. Optimally they should be under 50ms or less.
- Did a local EXPLAIN on query and actual was 2.096ms planning vs 0.130ms

Suggestions:
- Code wise I was not able to identify any issues with our queries. There are probably optimizations we could do, but more research would need to be done.
- We could get more information about these slow queries by adding additional logging. https://devcenter.heroku.com/articles/expensive-queries#identifying-slow-parameter-values.
- New relic also can provide us additional details. We have that setup but I don't know how much information about queries is being captured.
- I'd also recommend to see how much improvement the typeOrm upgrade will have on these. We should capture the before and after when that is released.
- Luckily the two slowest areas are not frequently called. Most hours they are hit only 1 to 5 times. So the performance improvement is not something that will need to be solved immediately
