### ISSUE TITLE
Core - first unit test on public 

### ISSUE THREAD

**Issue by kathyccheng** [bloom-housing/bloom#3217]
**Goal**

Now that we have unit tests in addition to Cypress tests on the public site, there is so much to test on this new smaller scale that we could start anywhere, but we could consider some of the below since they are unit testable and have been bugs in the past. It will probably require mock listing data.

Let's start in the listing detail sidebar in the get application section. It will probably be a test on ListingView.tsx.

**Example test**
The Apply Online button
* If an application is open and it is using the digital application, the Apply Now button should be present
* If it has the digital method but isn't open, the button should not show
* If it has a paper application method and not digital, it should not show

The whole sidebar has a lot of opportunity for something like this (e.g. if pick up address, then show the address, if paper methods, show the download button, etc) but we can start here.

**Comment by lisunshiny** [comment]
To make sure that I'm clear on the implementation here, by unit test do we mean non-Cypress tests that use the React testing library to test individual components by rendering them? I think I'm getting mixed up since the issue title is "first unit test on public" but there seems to be a [directory of at least a few unit tests](https://github.com/bloom-housing/bloom/blob/main/sites/public/__tests__) already on public 😅

Like this one: https://github.com/bloom-housing/bloom/blob/main/sites/public/__tests__/components/listing/GetApplication.test.tsx

And the ask to make more of them, but starting with listingview.tsx?

**Comment by lisunshiny** [comment]
Oh also there is also a command to run these unit tests on public, but they all fail -- `yarn test:unit` from sites/public

**Comment by lisunshiny** [comment]
Another update: I got the `render()` function to actually render a `<ListingView/>` without error! next steps are to add some actual unit tests.

Working branch here:
https://github.com/bloom-housing/bloom/compare/main...3217/add-listingview-unittest

**Comment by lisunshiny** [comment]
Feature branch has working tests now (there are an overwhelming number of things to test, but I scoped to just the apply online button per the issue recommendation). I think I'm failing an integration test though so I'll look into fixing that and then this will be ready to go up for review.
