### ISSUE TITLE
Spike Investigate use of Axios

### ISSUE THREAD

**Issue by YazeedLoonat** [bloom-housing/bloom#3223]
This came up in: https://github.com/housingbayarea/bloom/pull/561

I think we may want to investigate our use of axios/axios instances and figure out if we are using axios in the best way. We should take this time to also investigate if there is a better alternative.

**Comment by ludtkemorgan** [comment]
Findings:
I tackled two topics in this PR, should we keep axios and if so what changes should be made.

Should we stick with Axios:
- Pros:
  - Already used, so easy to keep using
  - We would need to come up with a new way to generate the backend-swagger which relies on axios. Front-end would also need to test every endpoint if we switch that up. This would not be a small amount of work.
  - We already pull axios in from other packages, so deleting it probably won’t really shrink our bundle
  - One of, if not the most, used library so easy to solve issues and library is well maintained
- Cons:
  - Very bulky 1.72mb unpacked sized vs 70kb gaxios.
  - Lots of other options: gaxios, got, node-fetch https://npmtrends.com/axios-vs-gaxios-vs-got-vs-https-vs-node-fetch. Some are better in performance and most are as easy to use as axios.
  - We already pull in all of the above mentioned from other packages so wouldn't increase bundle size.
  - we could get on the latest technology such as fetch instead of XMLHttp.

If we want to keep axios some recommended changes:
- For the most part it appears like we are using it correctly, vast majority of the api calls are working correctly with the one creation in the AuthContext.
  - The few times it doesn’t is because the useEffects are not getting completed by the time the new useEffect calls the api call. We could dig further into why, but I think all of those cases have been solved.
- We could update axios to the latest version. Would not have solved the issue that came up though.
- I personally would vote to change the name of AuthContext since it sets up the axios configuration as well. Or we could pull that out to a separate context that only does that.

Overall thoughts:
- At this time the benefits of switching to another library don't seem to be worth the work that it would take.
- We can update to the latest axios version easily and we can discuss as a team if the AuthContext change is desired.
