### ISSUE TITLE
Misleading Default Number of Bathrooms

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/bloom#3443]
When adding a new unit to a listing, the number of bathrooms field is not required, however, it is stored as zero on the backend if not filled out. As a result, saving the unit and listing causes the unit to functionally have the Shared bathroom selection. 

Technical Notes:
- This field should save as null when not filled out
-  Feedback from Product on how to handle the existing units that could either be explicitly or implicitly marked as having a Shared Bathroom.
- The Listings Export should be updated to show Shared rather than zero

https://github.com/bloom-housing/bloom/assets/53269332/20c3ce0d-7790-4a4d-9d34-45db27d5e245

QA: https://partners.bloom.exygy.dev/sign-in
1. Go to a listing
2. Add a unit without the number of bathrooms specified
3. Save the unit
4. Save the listing
5. Edit the listing
6. Clicking into the unit to see that the number of bathrooms is still not specified

**Comment by sarahlazarich** [comment]
I agree that if the bathroom field is not filled out, it should save as null, and that the listings export should be updated. 
In order to make sure we're not losing data, we should manually check listings since we've had the shared bathroom option and update the data. 

In general, we should store non-required fields that are not filled out as null instead of 0. @ColinBuyck  would you be able to list fields that show this behavior (storing 0 where required) for both hba and detroit?

**Comment by sarahlazarich** [comment]
Confirmed with Izzie here -- @ColinBuyck there should not be any issues with updating bathrooms with nothing entered to null instead of 0. No units are using the shared bathroom option currently. 

As for the other fields, I still think we should list them for each hba/detroit, look at the data, and make sure we aren't losing data going back.

**Comment by sarahlazarich** [comment]
this looks good!
