### ISSUE TITLE
Consistently use pluralized table names

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#349]
This is a bit of a nitpick, but I think it's worth getting sorted out before we have a production database that we have to migrate. I personally come from a pluralized table names background so I would lean that direction, but I realize there are advocates for both strategies. @bencpeters @pbn4 @software-project -- do any of you have strong opinions?

**Comment by pbn4** [comment]
@bk3c I'm more used to pluralized form too. No strong opinion on that.

**Comment by software-project** [comment]
Pluralized for me. Rails taking it's tow here on me ;)

**Comment by pbn4** [comment]
Interesting fact - the singular form seems to be the most upvoted answer for a stackoverflow discussion on [table-naming-dilemma-singular-vs-plural-names](https://stackoverflow.com/questions/338156/table-naming-dilemma-singular-vs-plural-names).

**Comment by pbn4** [comment]
> For extra credit, I think it might be good to break up the InitialDB migration into separate files of 1-2 tables each (and their associated indices, etc). I expect we're still going to be making object model changes over the next few weeks, and that seems like an easier way to keep track.

@bk3c There is a known issue for TypeORM where a big number of migrations hits startup time badly, so I propose we squash migrations into a single file once every few PRs land (during dev ofc). Also since we generate migrations from Typescript classes changes can be easily tracked by looking at class definition history.  I'd opt for not splitting initial migration into separate files since typeorm CLI does not expose an interface for generating a migration per entity and it introduces extra manual work and as noted before we can track changes from model definitions.
