### ISSUE TITLE
Lotteries - Listing opt in (FE + BE)

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4049]
https://www.figma.com/file/PAeCVANDmGdTz2Y53ouErM/Lotteries?type=design&node-id=3235-28691&mode=design&t=f8IRd445tNekl1aK-0

Adds a question to the listing that allows partners to opt in to using the lottery. As part of this, also update the preference copy in the screen above.

**Comment by sarahlazarich** [comment]
Once we get approval on the opt in design from Doorway, can we be sure to double check that we have the right design here?

I'm also hoping to talk through when the time comes: 
- Can we confirm that if a listing is not using the system lottery, what is going to happen to the lottery tab in Partners Portal? Assuming that it won't show up for any role type but want to confirm. 
- If the system lottery is disabled, we'll need to allow the manual upload/download now.

**Comment by emilyjablonski** [comment]
QA Notes
With the toggle on, create/edit a listing - in the rankings and results section, if the review order is lottery, a `Will the lottery be run in the partner portal?` question will toggle on. You should be able to save it as both values. When the toggle is saved as on, there will be new copy in the preference drawer. If the toggle is off, you should not be able to see the lottery tab.

**Comment by sarahlazarich** [comment]
I'm thinking we got a little out of sync on this one, I'm so sorry -- happy to talk on Weds if there are questions. Or maybe it's the permissioning here that's getting me turned around? I looked [here](https://partners.bloom.exygy.dev/users)

[design](https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3476-16542&m=dev)

Only the admin should be able to toggle a listing on/off from the system lottery. 
- So, If they indicate that a system lottery is being used, the partner should see the text after they indicate "Your lottery will be run in the Partners Portal. If you want to make alternative arrangements, please contact Doorway staff."
- If they indicate that a system lottery is not being used, the partner should see "This lottery will not be run in the Partners Portal because you have requested to use an alternative process. If this is an error, please contact Doorway staff."

**Comment by emilyjablonski** [comment]
@sarahlazarich 

This was merged before those changes were introduced - when we chatted w Em, this was the part I mentioned we would need a new ticket for

**Comment by sarahlazarich** [comment]
lgtm (QA'd for manual update - when system lottery is toggled off, I see post results button and can upload results. I don't otherwise)
