### ISSUE TITLE
Lotteries - Release & Retract Modal States (FE)

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/bloom#4142]
As an Admin that is re-running the lottery, I want to be prompted to confirm the action with the [re-run lottery modal](https://www.figma.com/file/PAeCVANDmGdTz2Y53ouErM/Lotteries?type=design&node-id=3235-29267&mode=design&t=f8IRd445tNekl1aK-0) before I do so, so that I do not proceed without understanding the implications of my actions. 

As an Admin that is releasing the lottery, I want to be prompted to confirm the action with the [lottery release modal](https://www.figma.com/file/PAeCVANDmGdTz2Y53ouErM/Lotteries?type=design&node-id=3235-29982&mode=design&t=f8IRd445tNekl1aK-0) before I do so, so that I understand that this action will allow property managers to view and publish results to applicants. 

As an Admin that is retracting the lottery, I want to be prompted to confirm the action with the
[retraction modal](https://www.figma.com/file/PAeCVANDmGdTz2Y53ouErM/Lotteries?type=design&node-id=3235-30033&mode=design&t=f8IRd445tNekl1aK-0) before I do so, so that I am made aware that this action is destructive. 

Notes: 
- We should make sure that records of confirmations are stored consistently through out tickets, especially [4048](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4048).
- In case it affects anything, we should remember that these actions also need to be logged in the history log. 

AC: 
- Only Admin users should have the ability to re-run, release, or retract lottery results.
- When an Admin re-runs a lottery, they should see a modal warning them of the implications of re-running the lottery and requiring them to confirm. 
- When an Admin releases a lottery, the user needs to confirm that they understand that they will be giving Partner users access to the lottery data, before continuing. 
- When an Admin retracts a lottery, they should see a a modal indicating that revoking a lottery is a destructive action.

**Comment by sarahlazarich** [comment]
Hi @emilyjablonski - Copy for these modals is linked [here](https://docs.google.com/document/d/130OuxoQnKnukoVr_SPQq57A0JZ4vycdcS9q0EX2Gkso/edit#heading=h.z2we68wtdnff)

**Comment by emilyjablonski** [comment]
QA Notes
On a closed listing that has a lottery, go to the lottery tab. The state in this PR is after a lottery has run. You can test that by manually updating the `lotteryLastRunAt` field to anything but null, or adding `listing.lotteryLastRunAt = new Date()` to the `lottery.tsx` file. You cannot test this right now in an external environment because we don't have a way to update lotteryLastRunAt but I'm happy to demo this locally until the backend part is complete.

Ensure the main card content looks as expected, and that when you click on each button, the modals look as expected ([Re-run modal Figma](https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3345-8231&t=YJpMBWGEZbaauHjn-0), [Release modal Figma](https://www.figma.com/design/PAeCVANDmGdTz2Y53ouErM/Lotteries?node-id=3345-8745&t=YJpMBWGEZbaauHjn-0))

**Comment by sarahlazarich** [comment]
@emilyjablonski seeing some weirdness with the release modal - strange because this wasn't present last week. Any idea what could be going on here?

https://www.loom.com/share/d71ac5cade32425381d66875460ff315?sid=323a72d9-1380-4629-9d41-682f5b68548b

**Comment by sarahlazarich** [comment]
Ok, I think the retract piece getting merged in fixed what I was seeing so this looks good!!
