### ISSUE TITLE
Lotteries - Public lottery view (applicant data)

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/bloom#4224]
Related to #4054

Includes "x applications were submitted for y units" and "out of x applicants on this list" as these may require backend changes to fetch that data in a performant way

We also need a way to fetch an application's rank and its preferences ranks, this could be a new lottery service call

**Comment by sarahlazarich** [comment]
Extra Complexity is that in order to know those numbers, we need to get a count of all of them 
If we need to do that every time someone loads that page, it could be a lot 
the "Blue Box" number is easier, but the other ones we'll need to know the total list count 

App number - will not include duplicates, # of applications included in the raw rank lottery 
Will be the new BE endpoint need to figure out how to do that 
Could we just store it when we do the lottery? We could! In a json or something

**Comment by emilyjablonski** [comment]
QA Notes
Submit an application to a listing and claim a preference. Run and release the lottery. Ensure that the rankings and the total number of applications and number of applications that claimed that preference are correct.

**Comment by sarahlazarich** [comment]
done!
