### ISSUE TITLE
ExpandableText fails in an unhelpful way if data passed in is undefined

### ISSUE THREAD

**Issue by akegan** [bloom-housing/bloom#446]
When trying to get the initial listing page to load, I'm getting this error:
![image](https://user-images.githubusercontent.com/11825994/88349467-058eda00-cd05-11ea-8ee6-60c1f29a73f1.png)

It's likely due to a value that we're missing in the listing, but I'm not sure that it's even a required value. I'm also not able to figure out which one it is from the error.

It'd be nice if ExpandableText either just rendered as empty, or raised a more specific error with a reference to the line number if the value is undefined.

Snippet of code that fails is e.g.
```
<ExpandableText className="text-sm text-gray-700">
  {listing.rentalHistory}
</ExpandableText>
```

**Comment by bk3c** [comment]
I'm pretty sure it's failing on

```
  if (props.children.length > maxLength) {
    button = moreLessButton(expanded, setExpanded)
  }
```

and it resolves props.children to null if listing.rentalHistory is null in your call. I agree that we need a better way of handling the error (and it should be easy enough with optional chaining), but I'm a little torn as to whether we should render empty or more obviously fail. I *think* I'd lean toward rendering the whole thing empty since a blank for a value doesn't seem like a crazy case, but does that mean we want to render the element empty (e.g. with a &nbsp as the only content) to maintain consistent layout, or do we want to not render anything at all?

(cc: @jaredcwhite @slowbot - thoughts?)
