### ISSUE TITLE
Allow address as alternative to lat/long for building address map

### ISSUE THREAD

**Issue by akegan** [bloom-housing/bloom#448]
Some jurisdictions (including SF) may not have Lat/Long locations for their buildings. It would be great to not have that be a required part of the buildingAddress in order for the map to show up.

It looks like we can use the [forward geocoder](https://docs.mapbox.com/mapbox-gl-js/example/marker-from-geocode/) to accomplish this 

This [ListingMap](https://github.com/bloom-housing/bloom/blob/master/shared/ui-components/src/page_components/listing/ListingMap.tsx)  the component that would need to be updated

**Comment by bk3c** [comment]
It was actually a somewhat purposeful choice, since geocoders often have trouble with new developments when the address didn't previously exist, or sometimes even the street itself is new.

I do think we could get the best of both worlds, where we used lat/lng when they were present on the object and then used the geocoder if they weren't. Does that sound like a reasonable solution?

**Comment by akegan** [comment]
yes! that sounds reasonable

**Comment by kathyccheng** [comment]
Working on this in #1545
