### ISSUE TITLE
Cleanup: swapping JSX.Element out for ReactNode

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#450]
We have a lot of interfaces with stuff like `JSX.Element` all the way to `string | JSX.Element | JSX.Element[]`

As I recently learned, it'd be great to standardize everything around `ReactNode` (or `React.ReactNode` depending on how you import it), since that will cover all those use cases (and is more readable!).

**Comment by bk3c** [comment]
It looks like there are 14 files with jsx.element, so I'm hoping it's not too huge of a lift. It's also nice to feel like we're getting a little more mature in our type usage.

Happy to have this happen whenever you need a break from more brain-intensive work.

**Comment by bk3c** [comment]
One other note here: there's a school of thought that the better way to include `props.children` is by using a type of `React.FC` for the components, so that's probably an option for some of these replacements too. See [this blog post](https://medium.com/better-programming/the-right-way-to-create-function-components-in-react-with-typescript-59dcf4076b92) for the argument.

@jaredcwhite Do you think it would be worth writing up a quick list of Bloom-preferred coding patterns and practices for the rest of the team to provide feedback on?

**Comment by jaredcwhite** [comment]
@bk3c I'll admit I'm not a huge fan of the added verbosity. Some docs I've seen recommend including the children props explicitly even when using the FC typing, so not sure it's a win.

On a general note though, I definitely think an overall coding style guide would be helpful. I'm also curious if we could draw on other open source guides of note and simply tweak as needed.
