### ISSUE TITLE
Cleanup: i18n: Eliminate duplication or improve organization of keys for application forms

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#458]
We've added a ton of keys to the `general.json` file for the application forms, and we're coming to a good place where we can take a group review of everything to find ways to deduce and organize everything well. Not sure what the best process is for this, so suggestions are most welcome.

**Comment by jaredcwhite** [comment]
So…in lieu of a better process, I'm just going to jot down random thoughts I as review the file. Everyone else is welcome to add comments as well.

* We have a `label` and a `t` category, and both seem to serve relatively the same purpose.
* There's an `application.form.errors` category but also errors mixed into the other sections.
* Some of the words/phrases in `application` are generic enough they should be in `t` or elsewhere.
* `application.form.options.states` seems like it could be out in its own category.
* `application.review.terms.text` would be good as Markdown text.
* Multiple spots where some labels are defined, such as `Please select one of the options above.`
* `application.start.whatToExpect.infoX` — should be a block of Markdown, no?

**Comment by kathyccheng** [comment]
@bk3c here are a couple of things that I found 

- timeout error is duplicated in `application.timeout` and in `authentication.timeout `
- streetaddress, apt, city name, and zip code placeholder text is repeated in `application.contact` and `application.alternateContact `
- firstname and lastname placeholder text is repeated in `application.name` and `application.alternateContact.name`
- phone number placeholder text is duplicated in `t` and `application.contact.phoneNumberFormPlaceHolder`
- the unitTypes list is repeated in `unitTypes` `and applications.preferredUnit.options `
- `application.chooseLanguage` should probably be renamed getStarted or something like that 
* I wonder if `listings.people` or `listings.person` should be in `t`
* There are a lot of form page specific errors that seem related to different validations but also a few more general ones in `application.form.errors`. I'm wondering if it might be helpful to pull out some of the specific ones like `firstNameError, lastNameError, emailAddressError, phoneNumberError, streetError, cityError, stateError, zipCodeError` since those feel like they might get reused in other places

**Comment by jaredcwhite** [comment]
Starting to get addressed in #686
