### ISSUE TITLE
Cleanup: identify ways to componentize parts of the application forms

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#459]
There are a couple of angles we can take on this:

* Move various parts of various forms into the shared `ui-components` package. For example, maybe a row with Date of Birth fields could be its own reusable component.
* Move most per-form-page logic into a Next app layout component, so there's less duplication from page to page.

Any other suggestions for a good approach?

**Comment by jaredcwhite** [comment]
As part of the form page cleanup: https://github.com/bloom-housing/bloom/pull/411#discussion_r461874607

**Comment by bencpeters** [comment]
My take on this is that we already have a decent UI library in `ui-components` - the existing generics `ProgressNav`, `FormCard`, etc. all seem like good reuseable, modular components. I think that unless we also add a library of "layouts" (more complete pages that just have predesignated content blocks to plug into) in `ui-components`, there's enough custom (meaning app-specific) logic in form pages that we probably want to keep it with the `public-reference` app, rather than a generic shared component. I **definitely** think that it should be consolidated to avoid duplication though, so I'd put in a vote for a layout component to do that. However, I don't think that we want to duplicate all the logic that is in `_app.jsx` right now, since that's where we are adding global providers/contexts, etc., and we may eventually have even more of that - having multiple "root level" layouts to keep in sync seems complicated to me.

We already have a `layouts/application.tsx` and `layouts/form.tsx` - to me it seems like these should be combined into a single application form layout component (probably moving the conductor definition to a separate "support"/"helper" file?). This is then the natural place to put essentially all of the shared page layout. We can render the main form page as `children`, and pass any necessary `props` to the layout component if there is any conditional rendering/custom logic that needs to be displayed (titles, telling the `ProgressNav` which page this is, etc.). 

More generally, we _could_ (and, IMO, should) refactor a lot of the layout boilerplate like head components, page metadata, header, footer, etc. into nested layout components, rather than having it repeated in a potentially error-prone manner in each entry in `pages` - this refactor could be a good opportunity to do it for all the pages, not just application form pages.

**Comment by jaredcwhite** [comment]
I agree that breaking some of the repetitive form code out into to a new Layout and perhaps a few layout-adjacent components is a good first step. I'd be happy to take a first stab at this.
