### ISSUE TITLE
[RFC] Front-end package and directory re-organization

### ISSUE THREAD

**Issue by bk3c** [bloom-housing/bloom#528]
Following recent discussions with @akegan and @james-wills-sf about making it easier to package common code for import rather than maintaining it in the reference implementation, I'd like to propose the following package and directory reorganization:

- Change the `apps/` top level directory to `sites/`, and generally change our naming to call those things sites rather than apps. The main reason for this is to avoid any potential confusion between "apps" and Applications, which will only get worse over time. I'm open to a name other than "sites", if anyone has a better idea.

- Rename the `@bloom-housing/core` package to be `@bloom-housing/site-core`. This will make it the clear home for common front-end code in addition to interfaces, and we can move logic that's shared between the public and partners apps there from ui-components (other than actual ui-components), plus aim to refactor as much as is reasonable there over time.

- Add `@bloom-housing/site-public` and `@bloom-housing/site-partners` packages to hold logic that we expect to be specific to one site or the other, but more general than the reference implementation. For example, the ApplicationConductor (or successor) will probably be unique to public, but it unlikely to be a point of customization so we're better of having it imported rather than have to maintain/diff/etc from the reference implementation to production sites. FWIW, I expect the partners package would grow to be substantially bigger than public over time, both in terms of code and dependency load size, so this gives us a way to keep the public site slimmed down but still have a place to abstract "core" code more cleanly from each reference ~~app~~ site.

I don't think this would change anything on the back-end in the short term.

Thoughts, @jaredcwhite, @dominikx96, @software-project, @bencpeters?

**Comment by jaredcwhite** [comment]
@bk3c I like all of the suggestions. Would we move some of the non-visual pieces of `ui-components` over to `site-core`?

**Comment by bk3c** [comment]
> @bk3c I like all of the suggestions. Would we move some of the non-visual pieces of `ui-components` over to `site-core`?

As many as we could.

**Comment by james-wills-sf** [comment]
This all seems good to me.

I'm fine with everything going in site-core with separate public/partners/shared folders or splitting them at the package level. I don't think either make much difference to us.

**Comment by jaredcwhite** [comment]
As discussed in Zoom earlier today, after trying out the move of some frontend-related code out of `shared/ui-components` and into `shared/core`, I ended up feeling like it was an increasing amount of complexity for no real gain in DX, and in fact I felt like maybe it's time to go in the opposite direction. So here's what I'm proposing:

* Move `shared/ui-components` to just `ui-components` file path in the monorepo and keep it the sole location where we have shared code for the frontend
* Remove `shared/core` altogether, and move the the frontend type interfaces out of there. We could either move them to:
  * `backend/core` — I tried this out (by putting them side a `types` subfolder) and it seem to work fine
  * `ui-components` — maybe this makes sense as then frontend types would be located alongside frontend components

I think we'll end up with needing less shared code in `ui-components` than we once thought because of #919, as we can work on improvements on the public or partners sites upstream and then merge downstream more easily.

Speaking of the Next apps, I would propose renaming them to:

* `sites/partners`
* `sites/public`

So in that case, our monorepo structure would become:

* `backend/core` (package name: `@bloom-housing/backend-core`)
* `sites/partners`
* `sites/public`
* `ui-components` (package name: `@bloom-housing/ui-components`)

Let me know what you think.

**Comment by jaredcwhite** [comment]
Oh, I forgot to mention we should sunset `services/listings` as well now that we have the new backend.

**Comment by dominikx96** [comment]
All suggestions sound good to me! 👍
