### ISSUE TITLE
Odd delays on bloom.exygy.dev

### ISSUE THREAD

**Issue by jaredcwhite** [bloom-housing/bloom#834]
After getting the backend DB working on Heroku for the dev site and the Next app rebuilt on Netlify, it's working now but there's an annoying delay of about 2-3 seconds clicking between the homepage and the listings page. Not sure why—something within the React code it seems, because pulling up the static page first is extremely quick.

**Comment by jaredcwhite** [comment]
We now have really bad delays on all dev and production sites (see https://housing.acgov.org).

**Comment by dominikx96** [comment]
I figured out what's the problem. The issue probably is after Next.js update, where getInitialProps run every time (also in client-side).

When the user clicks <Link>, after redirection, Next tries to fetch data from GET /listings endpoint, every time. it occurs over 1s delay and that's the reason why page load is so slow.

I spent a lot of time today to try to create a workaround for this, but without any results:

We should use getStaticProps and getStaticPaths to avoid re-fetch, instead of getInitialProps and exportPathMap.
Unfortunately, we still need a solution to create multi-lang routes. Of course, we can define the methods above for each page, but it seems like a lot of repeatable work.

Tried to use getStaticProps and exportPathMap (without use getStaticPaths), but seems impossible:
https://stackoverflow.com/questions/61432771/nextjs-how-do-i-get-exportpathmap-page-data-i-dont-see-it-in-getstaticprops

Also tried to use:

`if (typeof window === "undefined")`

condition inside getInitialProps, but it occurs missing data after <Link> redirection.

The one possible solution will be to use just pure <a> element, but we still need localization to redirect to the proper lang.

@jaredcwhite @software-project do you have ideas on how we can still create translations without repeat getStaticProps / workaround for re-fetching on the client-side?

**Comment by jaredcwhite** [comment]
Related to #509

**Comment by jaredcwhite** [comment]
Going to dive into this some more now.

**Comment by jaredcwhite** [comment]
So it looks like in order to make this work we'd have to remove our `exportPathMap` custom logic entirely and switch to the per-page static methods which @dominikx96 mentions above. A complicating factor is we'd also have to scrap our path logic and use Next's new i18n functionality (for static paths and locales to work well together) as detailed here:

https://nextjs.org/docs/advanced-features/i18n-routing

This all seems worthwhile for the performance win as well as less custom boilerplate code for us, but it also seems like a fairly big chunk of work. So will need to prioritize accordingly.

**Comment by jaredcwhite** [comment]
This might be good to implement while we're at it, both to help with testing this time around as well as monitor any future slowdowns. https://github.com/bloom-housing/bloom/issues/790

**Comment by kathyccheng** [comment]
Resolved in #1081
